# quarto render

project:
  type: website
  resources: 
    - "cc_full.csv"
    - "cleSac.txt"
    - "dem_score.csv"
    - "dem_score.xlsx"
    - "global13sdss_0.sav"
    - "imf_data.rds"
    - "le_mess.csv"
    - "periodic-table-data.csv"
    - "pnwflights23.xlsx"
    - "spotify_dataset.csv"
    - "wash-or_black.csv"
    - "202*-nba-over-under.html"
    - "critical_thinking_framework.pdf"
  output-dir: docs  # for GitHub Pages compatibility
  render:
    - index.qmd
    - about.qmd
    - consulting.qmd
    - workshops.qmd
    - talks.qmd
    - projects.qmd
    - ecots2k16/template_pkg.qmd

website:
  title: "Chester Ismay"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "Consulting"
        href: consulting.qmd
      - text: "Workshops"
        href: workshops.qmd
      - text: "Talks"
        href: talks.qmd
      - text: "Projects"
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/ismayc
      - icon: linkedin
        href: https://www.linkedin.com/in/chesterismay/
      - icon: twitter
        href: https://twitter.com/old_man_chester
      - icon: envelope
        href: mailto:chester.ismay@gmail.com

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
